### ISSUE TITLE
Questions about the using of symforce

### ISSUE THREAD

**Issue by zhanghua7099** [gisbi-kim/nano-pgo#2]
Hi! Thank you for sharing this good PGO project using Symforce. 

I am new in Symforce and have some questions about the use of Symforce in this project.

The **first question** is the setting of the epsilon. In your code,
https://github.com/gisbi-kim/nano-pgo/blob/e267621f32f747a677e4a9ab9c9b00b544d961dd/nano_pgo.py#L17
You set the epsilon as a number. In the symforce's epsilon tutorial, it provides other choices:
https://symforce.org/tutorials/epsilon_tutorial.html
Could you please give me some suggestions about the criteria for choosing `epsilon`?

The **second question** is about the using of the generated jacobians. In your code, 
https://github.com/gisbi-kim/nano-pgo/blob/e267621f32f747a677e4a9ab9c9b00b544d961dd/nano_pgo.py#L1374
If I'm right, the jacobian for each residual will be calculated individually, then they are stacked for optimization. Is my understanding correct?

**Comment by gisbi-kim** [comment]
Thank you for the valuable questions 

### A1) 
You'll encounter this warning if you **comment out that line** and run the code.
```
codegen.__init__():141 WARNING -- 
    Generating code with epsilon set to 0 - This is dangerous!  You may get NaNs, Infs,
    or numerically unstable results from calling generated functions near singularities.

    In order to safely generate code, you should set epsilon to either a symbol
    (recommended) or a small numerical value like `sf.numeric_epsilon`.  You should do
    this before importing any other code from symforce, e.g. with

        import symforce
        symforce.set_epsilon_to_symbol()

    or

        import symforce
        symforce.set_epsilon_to_number()

    For more information on use of epsilon to prevent singularities, take a look at the
    Epsilon Tutorial: https://symforce.org/tutorials/epsilon_tutorial.html
```

so you have two options, one is `set_epsilon_to_symbol` and one is `set_epsilon_to_number`

then, my experiment is: 
- first use the line symforce.set_epsilon_to_number(), and get the auto-generated file, let call it __between_error_codegen_using_set_epsilon_to_number.py 
- next use the line symforce.set_epsilon_to_symbol(), not the line symforce.set_epsilon_to_number(), and get the auto-generated file, let call it __between_error_codegen_using_set_epsilon_to_symbole.py 
- if you `diff` two files, they seem to be identical in this case (i.e., between factor) 

so I would like to give you my opinion for this question (Could you please give me some suggestions about the criteria for choosing epsilon?) is that you can use either from both and you could decide based on the empirical results.

### A2) 
- You are right. A residual in here was calculated individually. This single entity is sometimes called 'block', then you may have interest on this paper, [SLAM++-A highly efficient and temporally scalable incremental SLAM framework](https://www.researchgate.net/profile/Lukas-Polok-2/publication/314164153_SLAM_-A_highly_efficient_and_temporally_scalable_incremental_SLAM_framework/links/59d45ad2a6fdcc181ad956cd/SLAM-A-highly-efficient-and-temporally-scalable-incremental-SLAM-framework.pdf)

**Comment by zhanghua7099** [comment]
Thank you very much for your reply! I learned a lot.
