### ISSUE TITLE
Questions about the information matrix in the initialization step

### ISSUE THREAD

**Issue by zhanghua7099** [gisbi-kim/nano-pgo#4]
Hi! I found that the **information matrix** is set to the following lines:

https://github.com/gisbi-kim/nano-pgo/blob/b85562f0acda4d3e556f5b2d27c14156336df75b/nano_pgo.py#L560-L561

in the **initialization step**. Could you please give me some suggestions about how to set this information matrix in a real-world application? Are the parameters set manually, or is there a way to calculate this uncertainty automatically? 

Thank you for your help!

**Comment by gisbi-kim** [comment]
hi, @zhanghua7099 

It depends on your empirical results (so it is recommended for you to have a dataset with ground-truth trajectory and enough number of loop (revisit) events. For example, every robot has different wheel specs and different noise levels. so does every loop constraint generation algorithm. 

Based on my experience, it was wise to make the accuracy of odometry and loop constraint generation as similar as possible. Then, you can just use the same noise model for both. For instance, if lidar is used (lidar slam), the same algorithm (e.g., ICP) is applied to both odometry and loop constraints. However, if odometry uses a wheel sensor while loop constraints rely on a camera, it can be helpful to find an appropriate relative scale by gradually lowering the scale (typically down to one-tenth) for the sensor that is metrically less precise (generally the camera in this case).

**Comment by zhanghua7099** [comment]
Got it! Thank you very much for your reply! 

In `baseline_gtsam.py`, the **variances** of the noise model are also set to a fixed value. 
https://github.com/gisbi-kim/nano-pgo/blob/b85562f0acda4d3e556f5b2d27c14156336df75b/baseline_gtsam.py#L169-L171

https://github.com/gisbi-kim/nano-pgo/blob/b85562f0acda4d3e556f5b2d27c14156336df75b/baseline_gtsam.py#L177-L182

Are these parameters also determined through empirical results?

**Comment by gisbi-kim** [comment]
@zhanghua7099  good question! 

It was just set by no specific reasons but I confirmed it when I see the optimized trajectory is looking good, because here the codes are for the educational purpose. In real-world scenarios, you could also check the point cloud map generated by using the optimized poses is looking good too.
(ps. I used information and gtsam requires variances, which is the inverse of information)

**Comment by zhanghua7099** [comment]
I got it! Thank you for answering my question.
